<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>ll</string>
  </array>
  <key>name</key>
  <string>LLVM</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>captures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.comment.llvm</string>
        </dict>
      </dict>
      <key>match</key>
      <string>;.*</string>
      <key>name</key>
      <string>comment.line.semicolon.llvm</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(define)\b</string>
      <key>name</key>
      <string>keyword.control.llvm</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(ret|br|switch|indirectbr|invoke|resume|unreachable|add|fadd|sub|fsub|mul|fmul|udiv|sdiv|fdiv|urem|srem|frem|shl|lshr|ashr|and|or|xor|extractelement|insertelement|shufflevector|extractvalue|insertvalue|alloca|load|store|fence|cmpxchg|atomicrmw|getelementptr|trunc|zext|sext|fptrunc|fpext|fptoui|fptosi|uitofp|sitofp|ptrtoint|inttoptr|bitcast|icmp|fcmp|phi|select|call|va_arg|landingpad)\b</string>
      <key>name</key>
      <string>keyword.operator.llvm</string>
    </dict>
    <dict>
      <key>match</key>
      <string>(@[A-Za-z0-9_]+)</string>
      <key>name</key>
      <string>support.function.llvm</string>
    </dict>
    <dict>
      <key>match</key>
      <string>(%[A-Za-z0-9_]+)</string>
      <key>name</key>
      <string>variable.parameter.llvm</string>
    </dict>
    <dict>
      <key>match</key>
      <string>(![A-Za-z0-9_\.\"]+)</string>
      <key>name</key>
      <string>variable.parameter.llvm</string>
    </dict>
    <dict>
      <key>match</key>
      <string>((half|float|double|x86_fp80|fp128|ppc_fp128|i[0-9]+)\**|void|label)</string>
      <key>name</key>
      <string>storage.type.llvm</string>
    </dict>
  </array>
  <key>scopeName</key>
  <string>source.llvm</string>
  <key>uuid</key>
  <string>c8c7244b-ebce-4315-910b-75f34e4fe0c8</string>
</dict>
</plist>
