<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>td</string>
	</array>
	<key>name</key>
	<string>TableGen</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Single line comments.</string>
			<key>match</key>
			<string>\/\/.*</string>
			<key>name</key>
			<string>comment.line.double-slash.td</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numbers.</string>
			<key>match</key>
			<string>\b(?:\d+|0b[01]+|0x[\da-fA-F]+|\?|null_frag|true|false)\b</string>
			<key>name</key>
			<string>constant.numeric.td</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Class keyword.</string>
			<key>match</key>
			<string>^\b(?:multi)?class\b</string>
			<key>name</key>
			<string>storage.type.class.td</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Def keyword.</string>
			<key>match</key>
			<string>\bdefm?\b</string>
			<key>name</key>
			<string>storage.type.function.td</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Data types.</string>
			<key>match</key>
			<string>\b(?:bits?|code|dag|list|f\d+|i\d+|int|string)\b</string>
			<key>name</key>
			<string>storage.type.td</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>TableGen classes.</string>
			<key>match</key>
			<string>\b(?:AsmOperandClass|AsmParser|AsmParserVariant|AsmWriter|AssemblerPredicate|ComplexPattern|Format|InstrInfo|Instruction|Intrinsic|FPFormat|ImmType|InstrItinClass|Operand|Pat|PatFrag|PatLeaf|Pattern|Predicate|Processor|Register|RegisterClass|RegisterOperand|RegisterWithSubRegs|SDCallSeqEnd|SDCallSeqStart|SDNode|SDNodeProperty|SDNodeXForm|SDPatternOperator|SDTypeConstraint|SDTypeProfile|SubtargetFeature|Target|ValueType)\b</string>
			<key>name</key>
			<string>support.class.td</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>TableGen functions.</string>
			<key>match</key>
			<string>!(?:cast|empty|eq|foreach|head|if|strconcat|subst|tail)\b</string>
			<key>name</key>
			<string>support.function.td</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords.</string>
			<key>match</key>
			<string>\b(?:field|let)\b</string>
			<key>name</key>
			<string>keyword.td</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Control keywords.</string>
			<key>match</key>
			<string>\b(?:foreach|in)\b</string>
			<key>name</key>
			<string>keyword.control.td</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Include keyword.</string>
			<key>match</key>
			<string>\b(?:include)\b</string>
			<key>name</key>
			<string>keyword.control.import.td</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.td</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.td</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.td</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Bit slices.</string>
			<key>match</key>
			<string>{(\d+)}|{(\d+)-(\d+)}</string>
			<key>name</key>
			<string>keyword.operator.td</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.td</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Code fragments.</string>
			<key>end</key>
			<string>}\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.td</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.preprocessor.td</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Operators.</string>
					<key>match</key>
					<string>[&lt;&gt;]</string>
					<key>name</key>
					<string>keyword.operator.td</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:char|u?int(?:8|16|32|64)_t|long|short|signed|unsigned)\b</string>
					<key>name</key>
					<string>storage.type.int.td</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:do|if|else|for|return|while)\b</string>
					<key>name</key>
					<string>keyword.control.td</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Operators.</string>
			<key>match</key>
			<string>(?:\-&gt;)|[&amp;|!~.:=+\-\[\]]</string>
			<key>name</key>
			<string>keyword.operator.td</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Local variables.</string>
			<key>match</key>
			<string>\$[a-zA-Z_][\w_]+</string>
			<key>name</key>
			<string>variable.td</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>comment</key>
			<string>Double-quoted strings.</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.double.td</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\$\{[a-zA-Z_][\w_:]+\}|\$[a-zA-Z_][\w_]+</string>
					<key>name</key>
					<string>string.regexp.td</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.td</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Templates.</string>
			<key>end</key>
			<string>&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.td</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[a-zA-Z_][\w]*</string>
					<key>name</key>
					<string>variable.parameter.td</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.td</string>
	<key>uuid</key>
	<string>6233a58e-cb1d-4e1d-91b5-cb3778f87559</string>
</dict>
</plist>
